### ISSUE TITLE
php bin/initCacheWurfl.php fails

### ISSUE THREAD

**Issue by NielsLeenheer** [ThaDafinser/UserAgentParserComparison#7]
When I try to run the iniCacheWurfl.php script in the second step of the README it fails with the following errors:

```
$ php bin/initCacheWurfl.php 

PHP Fatal error:  Uncaught InvalidArgumentException: cannot locate [$inputFile] file! in /Users/niels/Projects/UserAgentParserComparison/vendor/mimmi20/wurfl/src/Device/Xml/AbstractIterator.php:56
Stack trace:
#0 /Users/niels/Projects/UserAgentParserComparison/vendor/mimmi20/wurfl/src/Device/DeviceRepositoryBuilder.php(91): Wurfl\Device\Xml\AbstractIterator->__construct('data/wurfl.xml')
#1 /Users/niels/Projects/UserAgentParserComparison/vendor/mimmi20/wurfl/src/Manager.php(291): Wurfl\Device\DeviceRepositoryBuilder->build('data/wurfl.xml', Array, Array)
#2 /Users/niels/Projects/UserAgentParserComparison/vendor/mimmi20/wurfl/src/Manager.php(211): Wurfl\Manager->init()
#3 /Users/niels/Projects/UserAgentParserComparison/bin/initCacheWurfl.php(36): Wurfl\Manager->reload()
#4 {main}
  thrown in /Users/niels/Projects/UserAgentParserComparison/vendor/mimmi20/wurfl/src/Device/Xml/AbstractIterator.php on line 56

Fatal error: Uncaught InvalidArgumentException: cannot locate [$inputFile] file! in /Users/niels/Projects/UserAgentParserComparison/vendor/mimmi20/wurfl/src/Device/Xml/AbstractIterator.php:56
Stack trace:
#0 /Users/niels/Projects/UserAgentParserComparison/vendor/mimmi20/wurfl/src/Device/DeviceRepositoryBuilder.php(91): Wurfl\Device\Xml\AbstractIterator->__construct('data/wurfl.xml')
#1 /Users/niels/Projects/UserAgentParserComparison/vendor/mimmi20/wurfl/src/Manager.php(291): Wurfl\Device\DeviceRepositoryBuilder->build('data/wurfl.xml', Array, Array)
#2 /Users/niels/Projects/UserAgentParserComparison/vendor/mimmi20/wurfl/src/Manager.php(211): Wurfl\Manager->init()
#3 /Users/niels/Projects/UserAgentParserComparison/bin/initCacheWurfl.php(36): Wurfl\Manager->reload()
#4 {main}
  thrown in /Users/niels/Projects/UserAgentParserComparison/vendor/mimmi20/wurfl/src/Device/Xml/AbstractIterator.php on line 56
```

**Comment by ThaDafinser** [comment]
I just updated the readme.

You need to download 2 files on yourself currently:
https://github.com/ThaDafinser/UserAgentParserComparison#installation
